language: python
matrix:
  include:
  - stage: client unit tests
    python: 3.4
    env:
    - TEST_SUITE="tests/uts/test_client.py"
  - python: 3.5
    env:
    - TEST_SUITE="tests/uts/test_client.py"
  - python: 3.6
    env:
    - TEST_SUITE="tests/uts/test_client.py"
  - python: 3.7
    env:
    - TEST_SUITE="tests/uts/test_client.py"
  - stage: agent unit tests
    python: 2.7
    env:
    - TEST_SUITE="tests/uts/test_agent.py"
  - stage: integration tests
    python: 3.4
    env:
    - TEST_SUITE="tests/integration"
    before_install:
    - tests/integration/setup.sh
  - python: 3.5
    env:
    - TEST_SUITE="tests/integration"
    before_install:
    - tests/integration/setup.sh
  - python: 3.6
    env:
    - TEST_SUITE="tests/integration"
    before_install:
    - tests/integration/setup.sh
  - python: 3.7
    env:
    - TEST_SUITE="tests/integration"
    before_install:
    - tests/integration/setup.sh
script: pytest $TEST_SUITE -v
dist: xenial
install:
- pip install --upgrade pip
- pip install -U importlib_metadata
- pip install .[test]
deploy:
  provider: pypi
  user: __token__
  password:
    secure: IbmdvH5PFfU74iQjRgtx6/dMbQIv+kSQhxOmPsB3KA7NGWWSeSn2Vjm8kb457x5Tau/rZwG8z6Q2lbbkgylAZ2H9OWUMw60ZtPJK351EGdljLqSFoaFxg60U7a8+dwSjhX91bRgqNYLF03oviRgVloYc/8/1b84tGFVelAJ6khZE+Ll6ndsqEtsCh9zSkd+PMlOWYTOhxUZu5hYUfpnwN1acnfhuNjGBlqvqTIA9ErTOxt50g0EBUT0Mzlkq0Wb70RaT6NCAI5NHIz/ZyVnk8hANyldoiuCpMsxSCq/DcQClHRiSDBo3sf9Glkeqk/tN0L1ZCT+ADxOs529Sj0got8VtlLY/qXRnUD+KqDXCEvtoLoGQantaG/HsFvESEHCdGo9EqHtPjLvhRQDZC/DxwUmCV2qKjtlrv/UflDLEg3cBKlDjLFzUFiliwjcJ3/Z9ljX5nm7k8/v4e014kncH6lBH2/wj7VhSBJ+6RM4mcocQt6wGdnWoc+66CO8PHKsjdTvasEp4V0D1WJqZN5n4W21L5vnQnUgSJ27eS8OZxWfnFZpzUnc4o67N32IOVKoZgnSY2TV/KXkZj4usEevDDtimH9fXAqImCZPyXc7Um/hP7YOiINGci18fOUFniDpJEIUIpm9K0Eu3s0JoFU2t4YxT68D7oThWwwY8PVJi+JI=
  on:
    tags: true
    branch: master
  skip_existing: true
notifications:
  slack:
    secure: pxpdYuQ/L/Naj+RpHJ7+JmxHs4sdl8vpZJCdgi9MuwaCqwskRnBz3/ySJHMn066BwszT3VsNBFddRBYdqT8o9MJrQiOv8dx+kY7RN4qGoYLymYJtDGugq5aMZMFV0JWE0ROJwRQBTAfUuESQ2MbaMiEQ1ohZ2LKm87NRRUG8A379sR214VZYhSUdtfPtSK5fbtNeVnT9sW+Lpz78Bv3mLE7ZzVBxrlU0SAT2lJl5VPOLgZLcy6mrvv7oyc3PpyoWUjlR/YPK4Anj7zItCbT3vnnDFw0Q0uHTjriyGJ4B4zVB8EgYbjFJS1N4jcY3PF9Z1sDNzp9pRyjUd1OSVUD3zynguvdv50Ug8WvuSGRAdFi6W+kfWBlaPlm7dRrkgx8f6rONE3fgrY+hCO4TN2YGnNNHHS+OniwTQ5/+oaRniElw6mVtdXzt0n5c0w3E6a6Gd7Okrbk7AXxSsi1qxPu+s5ptcvzzMeXEG/LPV6WmNRIiS/5wfszU4oiOtr0R2vyApBplFBMHDD6Ix0azfzgznq01o1R0wE4gOwnWKvvOEyYa/NlrHHKjjQNZWFr2JvHFrA/ObcloIeC+y6CuX+YWNaaMJDCoFaxaRkTp7d1CxgLCKV7uAbw+9jq/lnPiA9nLhPNmU81lZOYW/5a6guGwBcXAgqgnAv9hbpQkj4EMjxk=
